### POST /users/:_id/drum-machines
POST http://localhost:3000/users/640cf8676046e86bae85a52c/drum-machines
Authorization: Bearer 69
Content-Type: application/json

{
  "settings": {
  "bpm": 60,
  "timeSignature": 4,
  "instruments": [],
  "rhythmSequence": [],
  "rhythmGrid": [],
  "title": "test3"
  }
}

### GET /users/:_id/drum-machines
GET http://localhost:3000/users/640cf8676046e86bae85a52c/drum-machines
Authorization: Bearer 69

### GET /users/:_id/drum-machines/:dm_id
GET http://localhost:3000/users/640cf8676046e86bae85a52c/drum-machines/640d42d74db02eb486e32354
Authorization: Bearer 69

### PUT /users/:_id/drum-machines/:dm_id
PUT http://localhost:3000/users/640cf8676046e86bae85a52c/drum-machines/640ea359b22b68ccc36964d8
Authorization: Bearer 69
Content-Type: application/json

{
  "settings": {
  "bpm": 120,
  "timeSignature": 4,
  "instruments": [],
  "rhythmSequence": [],
  "rhythmGrid": [],
  "title": "edited test"
  }
}

### DELETE /users/:_id/drum-machines/:dm_id
DELETE http://localhost:3000/users/640cf8676046e86bae85a52c/drum-machines/640e81650a6170f6823a6e81
Authorization: Bearer 69