### Create Metronome ###
POST http://localhost:3000/users/oQc14dpGCkOzt19bZC5DHMX4LbT2/metronomes
Content-Type: application/json
Authorization: Bearer 69

{
  "settings": {
    "bpm": 120,
    "timeSignature": 4,
    "downBeat": true,
    "subdivide": 2,
    "mainBeat": true,
    "key": 0,
    "tone": "A440",
    "countIn": 1,
    "numMeasures": 4,
    "repeat": 1,
    "tempoInc": 0,
    "sectionPractice": true,
    "tempoPractice": true,
    "title": "Test Metronome 3"
  }
}


### Retrieve Metronomes for User ###
GET http://localhost:3000/users/640cf8676046e86bae85a52c/metronomes
Authorization: Bearer 69

### Retrieve Nonexistent User's Metronomes ###
GET  http://localhost:3000/users/notreal/metronomes

### Update Metronome ###
PUT  http://localhost:3000/users/640cf8676046e86bae85a52c/metronomes/64121e7c3bb2b97ad00a08d1
Content-Type: application/json
Authorization: Bearer 69

{
  "settings": {
    "bpm": 140,
    "timeSignature": 3,
    "downBeat": false,
    "subdivide": 3,
    "mainBeat": false,
    "key": 2,
    "tone": "A432",
    "countIn": 2,
    "numMeasures": 8,
    "repeat": 2,
    "tempoInc": 99,
    "sectionPractice": false,
    "tempoPractice": false,
    "title": "Updated Metronome 44"
  }
}


### Delete Metronome ###
DELETE http://localhost:3000/users/640cf8676046e86bae85a52c/metronomes/640d510e04d961add91f3442
Authorization: Bearer 69